version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend/app:/app/
    ports:
      - '5000:5000'
    environment:
      MONGODB_URI: mongodb://mongo:27017/nextjs_express_mongodb

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/usr/src/app/src
    ports:
      - '3000:3000'